# Generated by Django 6.0.2 on 2026-03-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
